module.exports = {
  "env": {
    "commonjs": true,
    "es6": true,
  },
  "extends": [
    "eslint-config-cc/eslintrc-base",
  ],
  "parserOptions": {
    "ecmaFeatures": {
      "experimentalObjectRestSpread": true,
      "jsx": true,
      "modules": true,
    },
    "ecmaVersion": 6,
    "sourceType": "module",
  },
  "plugins": [
    "react",
  ],
  "rules": {
    "arrow-body-style": [2, "as-needed"],
    "arrow-parens": [2, "always"],
    "arrow-spacing": [2],
    "constructor-super": [2],
    "generator-star-spacing": [2, "after"],
    "jsx-quotes": [2, "prefer-single"],
    "no-class-assign": [2],
    "no-confusing-arrow": [2, {"allowParens": true}],
    "no-const-assign": [2],
    "no-dupe-class-members": [2],
    "no-this-before-super": [2],
    "no-var": [2],
    "prefer-arrow-callback": [2],
    "prefer-const": [2],
    "prefer-spread": [2],
    "prefer-template": [2],
    "react/display-name": [2],
    "react/jsx-closing-bracket-location": [2, "tag-aligned"],
    "react/jsx-curly-spacing": [2, "never"],
    "react/jsx-indent-props": [2, 2],
    "react/jsx-no-duplicate-props": [2],
    "react/jsx-no-undef": [2],
    "react/jsx-uses-react": 1,
    "react/jsx-uses-vars": 1,
    "react/no-danger": [2],
    "react/no-did-mount-set-state": [2],
    "react/no-did-update-set-state": [2],
    "react/no-direct-mutation-state": [2],
    "react/no-unknown-property": [2],
    "react/prop-types": [2],
    "react/react-in-jsx-scope": [2],
    "react/self-closing-comp": [2],
    "react/sort-comp": [2],
    "react/sort-prop-types": [2],
    "require-yield": [2],
  },
}
